version: '3.4'

services:
  adminer:
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreConnection=Server=catalogdb;Port=5432;Database=shop_catalog;User Id=postgres;Password=password;
    ports:
      - "8000:80"
    depends_on:
      - catalogdb