version: '3.4'

services:
  adminer:
    image: adminer

  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3

  #kibana:
  #  image: docker.elastic.co/kibana/kibana:8.2.3


volumes:
  catalog_data:
  #elasticsearch-data: